version: "3"

services:
  huaweisolar:
    container_name: huaweisolar
    build: ./
    restart: unless-stopped
    environment:
      - INVERTER_IP=${INVERTER_IP}
      - INVERTER_PORT=${INVERTER_PORT}
      - MQTT_IP=${MQTT_IP}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - IMMEDIATE_VARS=${IMMEDIATE_VARS}
      - INSTALLATION_YEAR=${INSTALLATION_YEAR}
      - INSTALLATION_MONTH=${INSTALLATION_MONTH}
      - INSTALLATION_DAY=${INSTALLATION_DAY}
